export const VALID_CODE_MESSAGES = Object.freeze({
    NO_BALANCE:'NO_BALANCE',
    BALANCE_SHOULD_MULTIPLE_OF_TEN:'BALANCE_SHOULD_MULTIPLE_OF_TEN',
    BALANCE_SHOULD_MORE_THEN_TEN:'BALANCE_SHOULD_MORE_THEN_TEN',
    BALANCE_SHOULD_BE_NUMBER_TYPE:'BALANCE_SHOULD_BE_NUMBER_TYPE',
    SUCCESS:'SUCCESS',
    NO_QUANTITY:'NO_QUANTITY',
    QUANTITY_SHOULD_MORE_THEN_ONE:'QUANTITY_SHOULD_MORE_THEN_ONE',
    NO_NAME:'NO_NAME',
    NOT_ENOUGH_MONEY:'NOT_ENOUGH_MONEY',
})